CREATE TABLE IF NOT EXISTS project (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    desc TEXT,
    repo TEXT,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER IF NOT EXISTS updateProjectTimestamp
AFTER UPDATE ON project
BEGIN
    UPDATE project
    SET updateAt = CURRENT_TIMESTAMP
    WHERE id = NEW.id;
END;